In [1]:
import numpy as np


Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [5]:
array1 = np.random.randint(1,100, (50))

array1

array([87, 42, 15, 89, 93, 36, 50, 27, 49, 13, 22, 76, 94, 55, 43, 25, 17,
       38, 77,  2, 44, 30, 94, 18, 85, 67,  8, 47, 46, 44, 91, 72, 65, 79,
       73, 37, 78, 38, 91, 85, 99, 48, 74, 59, 44, 98, 14, 64, 54, 59],
      dtype=int32)

In [8]:
array1.size

50

In [15]:
np.where(array1 % 5 == 0)

(array([ 2,  6, 13, 15, 21, 24, 32, 39]),)

Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [16]:
array1d = np.random.randint(1, 21, (30))

array1d

array([11, 16,  7,  2,  3, 20, 20, 10, 13, 19, 18, 10,  7, 10, 19, 19,  8,
       18, 14, 20, 17, 19, 20,  8,  9,  2, 16,  6, 15,  4], dtype=int32)

In [17]:
array1d[1::2]

array([16,  2, 20, 10, 19, 10, 10, 19, 18, 20, 19,  8,  2,  6,  4],
      dtype=int32)

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [26]:
array2d = np.random.randint(1,50, (4,6))

array2d

array([[27,  1,  2, 39, 44, 47],
       [38, 17, 33, 37, 41, 44],
       [45, 25, 33, 10, 39, 26],
       [11, 43, 18, 39, 19, 28]], dtype=int32)

In [35]:
a_float = array2d.astype(float)

a_float

array([[27.,  1.,  2., 39., 44., 47.],
       [38., 17., 33., 37., 41., 44.],
       [45., 25., 33., 10., 39., 26.],
       [11., 43., 18., 39., 19., 28.]])

In [36]:
a_float = np.round(a_float, 2)

In [37]:
a_float

array([[27.,  1.,  2., 39., 44., 47.],
       [38., 17., 33., 37., 41., 44.],
       [45., 25., 33., 10., 39., 26.],
       [11., 43., 18., 39., 19., 28.]])

In [39]:
a2d = np.random.uniform(1,50, (4,5))
a2d = np.round(a2d, 2)
a2d

array([[43.58,  3.75, 16.8 , 12.3 , 13.28],
       [10.17,  4.69, 44.41,  6.9 , 45.98],
       [16.87,  4.26,  3.19,  6.9 ,  4.68],
       [30.55, 12.85, 19.06, 45.89, 31.13]])


Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [40]:
a3d = np.random.rand(2,3,5)
a3d = np.round(a3d, 1)
a3d

array([[[0.1, 1. , 0.5, 0.3, 0.5],
        [0.7, 0.2, 0. , 0.2, 0.2],
        [0.2, 0.7, 0.6, 0.6, 0.3]],

       [[0.2, 0.3, 0.3, 0.6, 0.8],
        [0.7, 0.2, 0.8, 0.6, 1. ],
        [0.1, 0.6, 0.7, 0.4, 0. ]]])

In [43]:
array3 = np.random.random(7)
array3 = np.round(array3, 4)
array3

array([0.3755, 0.7007, 0.7063, 0.2389, 0.2106, 0.3081, 0.6064])

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [51]:
array = np.empty_like(a3d, dtype=object)

In [59]:
array[np.mean(a3d) > a3d] = "B"
array[np.mean(a3d) < a3d] = "C"
array[np.mean(a3d) == a3d] = "A"
array[np. max == a3d] = "D"
array[np.min == a3d] = "E"

print(array)

[[['B' 'C' 'C' 'B' 'C']
  ['C' 'B' 'B' 'B' 'B']
  ['B' 'C' 'C' 'C' 'B']]

 [['B' 'B' 'B' 'C' 'C']
  ['C' 'B' 'C' 'C' 'C']
  ['B' 'C' 'C' 'B' 'B']]]


In [60]:
mean = np.mean(a3d)
maxi = np.max(a3d)
mini = np.min(a3d)

In [61]:
array[a3d > mean] = "B"
array[a3d < mean] = "C"
array[a3d == mean] = "A"
array[a3d == maxi] = "D"
array[a3d == mini] = "E"

print(a3d)
print("\n-------------------------\n")
print(array)

[[[0.1 1.  0.5 0.3 0.5]
  [0.7 0.2 0.  0.2 0.2]
  [0.2 0.7 0.6 0.6 0.3]]

 [[0.2 0.3 0.3 0.6 0.8]
  [0.7 0.2 0.8 0.6 1. ]
  [0.1 0.6 0.7 0.4 0. ]]]

-------------------------

[[['C' 'D' 'B' 'C' 'B']
  ['B' 'C' 'E' 'C' 'C']
  ['C' 'B' 'B' 'B' 'C']]

 [['C' 'C' 'C' 'B' 'B']
  ['B' 'C' 'B' 'B' 'D']
  ['C' 'B' 'B' 'C' 'E']]]
